### PR TITLE
Fix/close session

### PR DESCRIPTION
**Pull request by gswirski**
extracted retry and closeSession logic

### CODE REVIEW

**Review by simonmitchell — APPROVED** [review]
Really nice work thanks @gswirski !

**Comment by simonmitchell** [comment]
@gswirski just need to resolve the `.pbxpoj` merge conflict if you're happy to do so? :) Let me know if you'd rather I tackle!

**Comment by gswirski** [comment]
conflict resolved

**Review by simonmitchell — APPROVED** [review]

**Comment by simonmitchell** [comment]
Sorry I missed this! Thank you once again @gswirski ☺️

**Pull request merged**
